chore(MNYeBasisTradingStrategyExtension): Redeploy patched basis strategy [SIM-327]
SetProtocol/set-v2-strategies-deployments pull request #44
Opened 2022-05-11 17:29 UTC by richardliang

# Deployment Processes

## New/Updating Deployment Scripts
Before submitting a pull request for new scripts, make sure the following is done:
* Execution [doc](https://docs.google.com/document/d/1tO7Vz5CtFJlS6sAUxGW3hXGWEMYujdvaWs3KnmeDX1U/edit) is created and posted here: https://docs.google.com/document/d/1Y5jmnHxVRXZREVPHx7wUhkzJl8WXhZsvVhSdzvHXjEQ/edit#heading=h.44qcpgmr0xz1

MNYeBasisTradingStrategyExtension: [0xA33b9b89262D1f2E2c86c3306c1F20e845fb69bB](https://optimistic.etherscan.io/address/0xA33b9b89262D1f2E2c86c3306c1F20e845fb69bB)

2022-05-11 18:12 UTC, cgewecke approved these changes
LGTM!

2022-05-12 17:49 UTC, 0xSachinK requested changes

2022-05-12 17:49 UTC, 0xSachinK commented on optimism/deployments/constants/005_mny_eth_system.ts
> +  recenteringSpeed: ether(0.05),                        // N/A; Unused value; Can't be set to 0; Set to 0.05 to match FLI's speed
Can remove the `N/A; Unused value; Can't be set to 0;` part.

2022-05-12 18:00 UTC, 0xSachinK commented on optimism/deployments/constants/005_mny_eth_system.ts
> +  recenteringSpeed: ether(0.05),                        // N/A; Unused value; Can't be set to 0; Set to 0.05 to match FLI's speed
@richardliang lets also update the PR description with new contract addresses.

2022-05-20 10:52 UTC, merged